In [37]:
import numpy as np

# np.array() creates a simple array but pt list [] is a linkedlist
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr)

print('2nd element on 1st row: ', arr[0, 1]) # OR  arr[0][1]
print('number of dimensions :', arr.ndim)

print(arr[:2])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
2nd element on 1st row:  2
number of dimensions : 2
[[1 2 3]
 [4 5 6]]
