> # NumPy

In [13]:
import numpy as np

# np.array() creates a simple array but pt list [] is a linkedlist
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
vec = np.array([1,2,3,4,5,6,7,8,9])

print(arr,end="\n\n")
print(vec)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]


> ### Some basic functions

In [87]:
print('2nd element on 1st row: ', arr[0, 1]) # OR  arr[0][1]
print('number of dimensions :', arr.ndim)
print('shape of array:', arr.shape)
print('size of array:', arr.size)
print('data type of array:', arr.dtype)
print('size of each element in array:', arr.itemsize) # in bytes
print('the base array (view):',arr.base) # more info below
print('memory address of array:', arr.data)

2nd element on 1st row:  2
number of dimensions : 2
shape of array: (3, 3)
size of array: 9
data type of array: int32
size of each element in array: 4
the base array (view): None
memory address of array: <memory at 0x00000227CB63B1D0>


> ### Math operations on arrays 

In [ ]:

print("Matrix multiplication:", np.matmul(arr, arr))
print("Element-wise multiplication:", np.multiply(arr, arr))
print("Matrix addition:", np.add(arr, arr))
print("Matrix subtraction:", np.subtract(arr, arr))
print("Matrix division:", np.divide(arr, arr))
print("Matrix exponential:", np.exp(arr))
print("Matrix sine:", np.sin(arr))
print("Matrix cosine:", np.cos(arr))
print("Matrix tangent:", np.tan(arr))


> ### Array Slicing

- Arr[start:end:step]

In [65]:
print(vec[2:4])  # 2nd to 4th element
print(vec[:5])   # first to 5nd element
print(vec[2::2]) # start from 2nd index and skip 2 elements
print(arr[0:2, 1:3]) # 0 to 2 rows and 1 to 3 columns

[3 4]
[1 2 3 4 5]
[3 5 7 9]
[[2 3]
 [5 6]]


> ### Data Types:

- #### in python:
    - strings 
    - integer 
    - float 
    - boolean 
    - complex 

- ### in NumPy:

    - i - integer
    - b - boolean
    - u - unsigned integer
    - f - float
    - c - complex float
    - m - timedelta
    - M - datetime
    - O - object
    - S - string
    - U - unicode string
    - V - fixed chunk of memory for other type ( void )

In [76]:
print(arr.dtype)
arr2 = np.array([1, 2, 3, 4], dtype='U')
print(arr2.dtype)

int64
<U1


> ### Copy & View :

- #### on Edit :

In [95]:
x = arr.copy()
y = arr.view()

arr[0, 0] = 100

print(x ,end="\n\n")
print(y)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


- #### Base : 

In [96]:
print('x.base:', x.base)
print('y.base:', y.base)

x.base: None
y.base: [[100   2   3]
 [  4   5   6]
 [  7   8   9]]


> ### Reshaping Arrays :
- when i want reasheape array must: 
$$
n_0 × m_0 = n_1 × m_1
$$

In [103]:
vec = np.array([1,2,3,4,5,6,7,8,9])

vec = vec.reshape(3,3)
print(vec ,end="\n\n")
print('the base of vec after rechape:',vec.base)

vec = vec.reshape(-1) # is used to flatten() the array
print('vec after flatten:',vec ,end="\n\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

the base of vec after rechape: [1 2 3 4 5 6 7 8 9]
vec after flatten:  [1 2 3 4 5 6 7 8 9]



> ### Joining Array : 


- #### Vectors :

In [15]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr3 = np.concatenate((arr1, arr2))

print(arr3)


[1 2 3 4 5 6]


- #### 2D-Arrays :
    - axis :
    <!-- ![aixs_img](./img/img_01.png) -->
    <div style="display:flex;justify-content:center">
        <img title="a title" alt="Alt text" src="./img/img_01.png" style="width:50vw;filter: invert(0.95);">
    </div>

In [19]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

print(np.concatenate((arr1, arr2), axis=0),end="\n\n")
print(np.concatenate((arr1, arr2), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


`there are other ways to join arrays: stack() hstack() vstack() dstack() column_stack() row_stack() concatenate()`
 

> ### Splitting Array :

In [22]:
arr4 = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr4, 3) # the divider must be lthe length of the array

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


> ### Searching Arrays :

In [23]:
arr5 = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr5 == 4) # returns a tuple with the index of the element

print(x) 

(array([3, 5, 6], dtype=int64),)


In [24]:
x = np.where(arr5%2 == 0) 

print(x)

(array([1, 3, 5, 6], dtype=int64),)


> ### Sorting Arrays :

In [25]:
s = np.sort(arr5)
s2 = np.sort(arr5)[::-1] # reverse sort
s3 = np.sort(arr5, kind='mergesort') # sort using mergesort

print(s)
print(s2)

[1 2 3 4 4 4 5]
[5 4 4 4 3 2 1]


#### kind Values:

|   kind      | speed | worst case | work space | stable |
|-------------|-------|------------|------------|--------|
| 'quicksort' |   1   |   O(n^2)   |     0      |   no   |
| 'heapsort'  |   3   | O(n*log(n))|     0      |   no   |
| 'mergesort' |   2   | O(n*log(n))|   ~n/2     |  yes   |
| 'timsort'   |   2   | O(n*log(n))|   ~n/2     |  yes   |



> ### Filtering Arrays :

In [26]:
arr6 = np.array([41, 42, 43, 44])

var_filter = [True, False, True, False]
var_filter2 = arr6 > 42

newarr = arr6[var_filter]
newarr2 = arr6[var_filter2]

print(newarr)
print(newarr2)

[41 43]
[43 44]
